//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.RewardAndRecognition {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.RewardAndRecognition.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   あなたの新しいアワードキャプテンは... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdminHeaderText {
            get {
                return ResourceManager.GetString("AdminHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} - {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdminSubheaderText {
            get {
                return ResourceManager.GetString("AdminSubheaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークプレースアワードのタブを開いてリワードサイクルの設定と管理を行いましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdminTabNavigationText {
            get {
                return ResourceManager.GetString("AdminTabNavigationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたはこの賞について **{0}** を指示しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyEndorsedMessage {
            get {
                return ResourceManager.GetString("AlreadyEndorsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受賞者は... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AwardWinnerCardTitle {
            get {
                return ResourceManager.GetString("AwardWinnerCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アワードキャプテンの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigureAdminTitle {
            get {
                return ResourceManager.GetString("ConfigureAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備はよろしいですか？アワードキャプテンを選びましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このリワードサイクルは終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CycleClosedMessage {
            get {
                return ResourceManager.GetString("CycleClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在アクティブなリワードサイクルはありません。チームメンバーへのノミネートや支持を行うには、次のアワードサイクルまでお待ちください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CycleValidationMessage {
            get {
                return ResourceManager.GetString("CycleValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支持する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndorseButtonText {
            get {
                return ResourceManager.GetString("EndorseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支持する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndorseTitle {
            get {
                return ResourceManager.GetString("EndorseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しました。数分後に再度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このチームではボットが追加されていないので使用ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidTeamText {
            get {
                return ResourceManager.GetString("InvalidTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないテナントIDが見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * 指定されたアワードへのチームメンバーの推薦を許可してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageAwardsBulletPoint {
            get {
                return ResourceManager.GetString("ManageAwardsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリは個人チャットやグループチャットでは使用できません。アワードを送信するには、ワークプレースアワードが追加されているチームに移動してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagingExtensionErrorMessage {
            get {
                return ResourceManager.GetString("MessagingExtensionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * ノミネートされたチームメンバーの中からアワードの受賞者を承認し、発行しましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NominateBulletPoint {
            get {
                return ResourceManager.GetString("NominateBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノミネートする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NominateButton {
            get {
                return ResourceManager.GetString("NominateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すぐにノミネートする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NominateButtonText {
            get {
                return ResourceManager.GetString("NominateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} にノミネートされました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NominatedByText {
            get {
                return ResourceManager.GetString("NominatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} はこのアワードにノミネートされています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NominatePeopleTitle {
            get {
                return ResourceManager.GetString("NominatePeopleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} はこのアワードにノミネートされています。 - {1} . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NominationMentionText {
            get {
                return ResourceManager.GetString("NominationMentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノミネートはまもなく終了します。今すぐノミネートしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NominationReminderNotificationText {
            get {
                return ResourceManager.GetString("NominationReminderNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ** チーム所有者からのお知らせ ** {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoteForTeamText {
            get {
                return ResourceManager.GetString("NoteForTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リワードサイクルは **{0}** から *{1}** に構成されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RewardCycleHeader {
            get {
                return ResourceManager.GetString("RewardCycleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リワードサイクル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RewardCycleText {
            get {
                return ResourceManager.GetString("RewardCycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リワードタイムです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RewardTitle {
            get {
                return ResourceManager.GetString("RewardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アワードキャプテンを設定しましょう。アワードキャプテンはアワードを立ち上げ、ノミネーションを管理できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetAdminBulletPoint {
            get {
                return ResourceManager.GetString("SetAdminBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アワードキャプテンの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetAdminButtonText {
            get {
                return ResourceManager.GetString("SetAdminButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アワードキャプテンとして、{0}はアワードを立ち上げ、アワードサイクルを設定し、結果を共有します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetAdminMentionText {
            get {
                return ResourceManager.GetString("SetAdminMentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * 支持することでノミネートされたメンバーを支援する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetRewardCycleBulletPoint {
            get {
                return ResourceManager.GetString("SetRewardCycleBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **{0}** への **{1}** のノミネーションを支持しました。結果は **{2}** にて共有されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuccessfulEndorseMessage {
            get {
                return ResourceManager.GetString("SuccessfulEndorseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なコマンドです。次のコマンドを試してみてください： -Nominate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnsupportedBotCommand {
            get {
                return ResourceManager.GetString("UnsupportedBotCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **ワークプレースアワードのタブで発行された結果をみる。** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewWinnerTabText {
            get {
                return ResourceManager.GetString("ViewWinnerTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **アワードキャプテンがチームから抜けました。リワードサイクルを進めるには新しいアワードキャプテンを選んでください** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardNewAdminText {
            get {
                return ResourceManager.GetString("WelcomeCardNewAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のようなタスクをお手伝いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   こんにちは。Workplace Awardsボットです。パフォーマンスアワードへのチームメンバーの推薦をお手伝いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リワードサイクル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WinnerCardRewardCycleTitle {
            get {
                return ResourceManager.GetString("WinnerCardRewardCycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   おめでとうございます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WinnerMentionText {
            get {
                return ResourceManager.GetString("WinnerMentionText", resourceCulture);
            }
        }
    }
}
